name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # har raat 12 baje run karega
  workflow_dispatch:       # manually bhi trigger kar sakta hai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: RajatDjangoDeveloper
          outputs: dist/github-contribution-grid-snake.svg

      - name: Upload to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

